let KanjiArray = [{
    "name": "一",
    "kun": "ひと- ・ ひと.つ",
	"on": "イチ ・ イツ",
    "meaning": "NHẤT",
	"part": "",
},{
    "name": "万",
    "kun": "よろず",
	"on": "マン ・ バン",
    "meaning": "VẠN, MẶC",
	"part": "一 NHẤT",
},{
    "name": "六",
    "kun": "む ・ む.つ ・ むっ.つ ・ むい",
	"on": "ロク ・ リク",
    "meaning": "LỤC",
	"part": "亠 ĐẦU ・ 八 BÁT",
},{
    "name": "友",
    "kun": "とも",
	"on": "ユウ",
    "meaning": "HỮU",
	"part": "又 HỰU",
},{
    "name": "名",
    "kun": "な ・ -な",
	"on": "メイ ・ ミョウ",
    "meaning": "DANH",
	"part": "夕 TỊCH ・ 口 KHẨU",
},{
    "name": "木",
    "kun": "き ・ こ-",
	"on": "ボク ・ モク",
    "meaning": "MỘC",
	"part": "",
},{
    "name": "来",
    "kun": "く.る ・ きた.る ・ きた.す ・ き.たす ・ き.たる ・ き ・ こ",
	"on": "ライ ・ タイ",
    "meaning": "LAI, LÃI",
	"part": "米 MỄ",
},{
    "name": "毎",
    "kun": "ごと ・ -ごと.に",
	"on": "マイ",
    "meaning": "MỖI",
	"part": "毋 VÔ, MƯU",
},{
    "name": "話",
    "kun": "はな.す ・ はなし",
	"on": "ワ",
    "meaning": "THOẠI",
	"part": "言 NGÔN, NGÂN ・ 舌 THIỆT",
}]